services:
  - type: web
    name: oy-zametka
    runtime: dotnet
    branch: main
    buildCommand: "dotnet publish -c Release -o out"
    startCommand: "dotnet out/ZametkiApp.dll"
    publishPath: out
